  name: Friend
  version: '1.0-BETA'
  main: org.youfriend.Friend
  api-version: '1.21'
  commands:
    #friendadd:
     # description: friendadd
 #     usage: /<command> <friendName>
 #   friendyes:
 #     description: accept friend
 #     usage: /<command>
 #   friendno:
 #     description: deny friend
 #     usage: /<command>
 #   friendremove:
 #     description: deny friend
 #     usage: /<command> <friendName>
 #   friendlist:
 #     description: deny friend
 #     usage: /<command> <friendName>
    friend:
      description: all friend commands use
      usage: /<command> <action>
      aliases:
        - friend add
        - friend list
        - friend remove
        - friend accept
        - friend deny
        - friend sendmail
        - friend readmail
        - friend menu
        - friend zenly