name: Friend
version: '1.0-BETA'
main: org.youfriend.Friend
api-version: '1.21'
commands:
  addfriend:
    description: add freind
    usage: /<command> <friendName>
  friendyes:
    description: accept friend
    usage: /<command>